name: Daily Operations

on:
  schedule:
    - cron: "0 7 * * *" # Runs at 7:00 AM UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  run-daily-operations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run daily operations
        run: node src/main.js
        env:
          CURRENT_KYU: ${{ secrets.CURRENT_KYU }}
          TAG_PREFERENCES: ${{ secrets.TAG_PREFERENCES }}
          KATAS_PER_DAY: ${{ secrets.KATAS_PER_DAY }}
          PREFERRED_LANGUAGE: ${{ secrets.PREFERRED_LANGUAGE }}
          MIN_UNSOLVED_KATAS: ${{ secrets.MIN_UNSOLVED_KATAS }}
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          GITHUB_COMMITTER_NAME: ${{ secrets.GITHUB_COMMITTER_NAME }}
          GITHUB_COMMITTER_EMAIL: ${{ secrets.GITHUB_COMMITTER_EMAIL }}
