name: Weekly Kata Update
on:
  schedule:
    - cron: "0 0 * * 0" # Runs at midnight UTC every Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  update-kata-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run unified kata update
        run: npm run update-katas
        env:
          CURRENT_KYU: ${{ secrets.CURRENT_KYU }}
          TAG_PREFERENCES: ${{ secrets.TAG_PREFERENCES }}
          PREFERRED_LANGUAGE: ${{ secrets.PREFERRED_LANGUAGE }}
          MIN_UNSOLVED_KATAS: ${{ secrets.MIN_UNSOLVED_KATAS }}
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
