name: Weekly Kata Update
on:
  schedule:
    - cron: "0 0 * * 0" # Runs at midnight UTC every Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  update-kata-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Run unified kata update
        run: node scripts/unifiedKataUpdate.js
        env:
          CURRENT_KYU: ${{ secrets.CURRENT_KYU }}
          TAG_PREFERENCES: ${{ secrets.TAG_PREFERENCES }}
          PREFERRED_LANGUAGE: ${{ secrets.PREFERRED_LANGUAGE }}
          MIN_UNSOLVED_KATAS: ${{ secrets.MIN_UNSOLVED_KATAS }}
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GH_PASSWORD }}
          # Add other necessary environment variables
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/katas.db
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update kata database" && git push)
